//go:build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package facade

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacadeServiceEnv) DeepCopyInto(out *FacadeServiceEnv) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacadeServiceEnv.
func (in *FacadeServiceEnv) DeepCopy() *FacadeServiceEnv {
	if in == nil {
		return nil
	}
	out := new(FacadeServiceEnv)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FacadeServiceSpec) DeepCopyInto(out *FacadeServiceSpec) {
	*out = *in
	out.Env = in.Env
	if in.GatewayPorts != nil {
		in, out := &in.GatewayPorts, &out.GatewayPorts
		*out = make([]GatewayPorts, len(*in))
		copy(*out, *in)
	}
	if in.AllowVirtualHosts != nil {
		in, out := &in.AllowVirtualHosts, &out.AllowVirtualHosts
		*out = new(bool)
		**out = **in
	}
	if in.Ingresses != nil {
		in, out := &in.Ingresses, &out.Ingresses
		*out = make([]IngressSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FacadeServiceSpec.
func (in *FacadeServiceSpec) DeepCopy() *FacadeServiceSpec {
	if in == nil {
		return nil
	}
	out := new(FacadeServiceSpec)
	in.DeepCopyInto(out)
	return out
}
