MEMORY_LIMIT: "64Mi"
CPU_REQUEST: "50m"
CPU_LIMIT: "200m"
FACADE_GATEWAY_REPLICAS: 2
FACADE_GATEWAY_MEMORY_LIMIT: "32Mi"
FACADE_GATEWAY_CPU_LIMIT: "1"
FACADE_GATEWAY_CPU_REQUEST: "100m"
HPA_ENABLED: false
HPA_AVG_CPU_UTILIZATION_TARGET_PERCENT: 75
HPA_SCALING_UP_STABILIZATION_WINDOW_SECONDS: 60
HPA_SCALING_UP_PODS_PERIOD_SECONDS: 60
HPA_SCALING_UP_PODS_VALUE: 1
HPA_SCALING_DOWN_STABILIZATION_WINDOW_SECONDS: 300
HPA_SCALING_DOWN_PODS_PERIOD_SECONDS: 60
HPA_SCALING_DOWN_PODS_VALUE: 1
HPA_MIN_REPLICAS: 2
HPA_MAX_REPLICAS: 5
HPA_SCALING_UP_SELECT_POLICY: Max
HPA_SCALING_DOWN_SELECT_POLICY: Max
HPA_SCALING_UP_PERCENT_PERIOD_SECONDS: -1
HPA_SCALING_DOWN_PERCENT_PERIOD_SECONDS: -1