// Code generated by MockGen. DO NOT EDIT.
// Source: k8s.io/client-go/util/workqueue (interfaces: RateLimitingInterface)
//
// Generated by this command:
//
//	mockgen --destination=./workqueue/stub_workqueue.go --package=mock_workqueue --build_flags=--mod=mod k8s.io/client-go/util/workqueue RateLimitingInterface
//

// Package mock_workqueue is a generated GoMock package.
package mock_workqueue

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRateLimitingInterface is a mock of RateLimitingInterface interface.
type MockRateLimitingInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRateLimitingInterfaceMockRecorder
	isgomock struct{}
}

// MockRateLimitingInterfaceMockRecorder is the mock recorder for MockRateLimitingInterface.
type MockRateLimitingInterfaceMockRecorder struct {
	mock *MockRateLimitingInterface
}

// NewMockRateLimitingInterface creates a new mock instance.
func NewMockRateLimitingInterface(ctrl *gomock.Controller) *MockRateLimitingInterface {
	mock := &MockRateLimitingInterface{ctrl: ctrl}
	mock.recorder = &MockRateLimitingInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRateLimitingInterface) EXPECT() *MockRateLimitingInterfaceMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockRateLimitingInterface) Add(item any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Add", item)
}

// Add indicates an expected call of Add.
func (mr *MockRateLimitingInterfaceMockRecorder) Add(item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockRateLimitingInterface)(nil).Add), item)
}

// AddAfter mocks base method.
func (m *MockRateLimitingInterface) AddAfter(item any, duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddAfter", item, duration)
}

// AddAfter indicates an expected call of AddAfter.
func (mr *MockRateLimitingInterfaceMockRecorder) AddAfter(item, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAfter", reflect.TypeOf((*MockRateLimitingInterface)(nil).AddAfter), item, duration)
}

// AddRateLimited mocks base method.
func (m *MockRateLimitingInterface) AddRateLimited(item any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddRateLimited", item)
}

// AddRateLimited indicates an expected call of AddRateLimited.
func (mr *MockRateLimitingInterfaceMockRecorder) AddRateLimited(item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRateLimited", reflect.TypeOf((*MockRateLimitingInterface)(nil).AddRateLimited), item)
}

// Done mocks base method.
func (m *MockRateLimitingInterface) Done(item any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Done", item)
}

// Done indicates an expected call of Done.
func (mr *MockRateLimitingInterfaceMockRecorder) Done(item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Done", reflect.TypeOf((*MockRateLimitingInterface)(nil).Done), item)
}

// Forget mocks base method.
func (m *MockRateLimitingInterface) Forget(item any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Forget", item)
}

// Forget indicates an expected call of Forget.
func (mr *MockRateLimitingInterfaceMockRecorder) Forget(item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Forget", reflect.TypeOf((*MockRateLimitingInterface)(nil).Forget), item)
}

// Get mocks base method.
func (m *MockRateLimitingInterface) Get() (any, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRateLimitingInterfaceMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRateLimitingInterface)(nil).Get))
}

// Len mocks base method.
func (m *MockRateLimitingInterface) Len() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Len")
	ret0, _ := ret[0].(int)
	return ret0
}

// Len indicates an expected call of Len.
func (mr *MockRateLimitingInterfaceMockRecorder) Len() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Len", reflect.TypeOf((*MockRateLimitingInterface)(nil).Len))
}

// NumRequeues mocks base method.
func (m *MockRateLimitingInterface) NumRequeues(item any) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NumRequeues", item)
	ret0, _ := ret[0].(int)
	return ret0
}

// NumRequeues indicates an expected call of NumRequeues.
func (mr *MockRateLimitingInterfaceMockRecorder) NumRequeues(item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NumRequeues", reflect.TypeOf((*MockRateLimitingInterface)(nil).NumRequeues), item)
}

// ShutDown mocks base method.
func (m *MockRateLimitingInterface) ShutDown() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ShutDown")
}

// ShutDown indicates an expected call of ShutDown.
func (mr *MockRateLimitingInterfaceMockRecorder) ShutDown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShutDown", reflect.TypeOf((*MockRateLimitingInterface)(nil).ShutDown))
}

// ShutDownWithDrain mocks base method.
func (m *MockRateLimitingInterface) ShutDownWithDrain() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ShutDownWithDrain")
}

// ShutDownWithDrain indicates an expected call of ShutDownWithDrain.
func (mr *MockRateLimitingInterfaceMockRecorder) ShutDownWithDrain() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShutDownWithDrain", reflect.TypeOf((*MockRateLimitingInterface)(nil).ShutDownWithDrain))
}

// ShuttingDown mocks base method.
func (m *MockRateLimitingInterface) ShuttingDown() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShuttingDown")
	ret0, _ := ret[0].(bool)
	return ret0
}

// ShuttingDown indicates an expected call of ShuttingDown.
func (mr *MockRateLimitingInterfaceMockRecorder) ShuttingDown() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShuttingDown", reflect.TypeOf((*MockRateLimitingInterface)(nil).ShuttingDown))
}
